services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=reisfranco
      - POSTGRES_PASSWORD=reisfranco123
      - POSTGRES_DB=task-manager
